///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace e3Validation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the e3ValidationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("165c054d-831d-4927-9349-478e9651b92f")]
    public partial class e3ValidationRepository : RepoGenBaseFolder
    {
        static e3ValidationRepository instance = new e3ValidationRepository();
        e3ValidationRepositoryFolders.ComEnclarapharmaciaE3MobileappAppFolder _comenclarapharmaciae3mobileapp;

        /// <summary>
        /// Gets the singleton class instance representing the e3ValidationRepository element repository.
        /// </summary>
        [RepositoryFolder("165c054d-831d-4927-9349-478e9651b92f")]
        public static e3ValidationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public e3ValidationRepository() 
            : base("e3ValidationRepository", "/", null, 0, false, "165c054d-831d-4927-9349-478e9651b92f", ".\\RepositoryImages\\e3ValidationRepository165c054d.rximgres")
        {
            _comenclarapharmaciae3mobileapp = new e3ValidationRepositoryFolders.ComEnclarapharmaciaE3MobileappAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("165c054d-831d-4927-9349-478e9651b92f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ComEnclarapharmaciaE3Mobileapp folder.
        /// </summary>
        [RepositoryFolder("26df83d2-8b55-4282-b6e9-1f4ff84678e5")]
        public virtual e3ValidationRepositoryFolders.ComEnclarapharmaciaE3MobileappAppFolder ComEnclarapharmaciaE3Mobileapp
        {
            get { return _comenclarapharmaciae3mobileapp; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class e3ValidationRepositoryFolders
    {
        /// <summary>
        /// The ComEnclarapharmaciaE3MobileappAppFolder folder.
        /// </summary>
        [RepositoryFolder("26df83d2-8b55-4282-b6e9-1f4ff84678e5")]
        public partial class ComEnclarapharmaciaE3MobileappAppFolder : RepoGenBaseFolder
        {
            e3ValidationRepositoryFolders.LinearFolder _linear;
            RepoItemInfo _homepagemenuInfo;

            /// <summary>
            /// Creates a new ComEnclarapharmaciaE3Mobileapp  folder.
            /// </summary>
            public ComEnclarapharmaciaE3MobileappAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ComEnclarapharmaciaE3Mobileapp", "/mobileapp[@title='com.enclarapharmacia.E3Mobileapp']", parentFolder, 30000, null, false, "26df83d2-8b55-4282-b6e9-1f4ff84678e5", "")
            {
                _linear = new e3ValidationRepositoryFolders.LinearFolder(this);
                _homepagemenuInfo = new RepoItemInfo(this, "HomepageMenu", "?/?/toolbar/?/?/container[@contentdescription='  Patients, OK']/container[1]/picture[1]", 30000, null, "c6b8d12a-d221-4cbb-9dcb-b966626ee7e9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("26df83d2-8b55-4282-b6e9-1f4ff84678e5")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("26df83d2-8b55-4282-b6e9-1f4ff84678e5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HomepageMenu item.
            /// </summary>
            [RepositoryItem("c6b8d12a-d221-4cbb-9dcb-b966626ee7e9")]
            public virtual Ranorex.Picture HomepageMenu
            {
                get
                {
                    return _homepagemenuInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The HomepageMenu item info.
            /// </summary>
            [RepositoryItemInfo("c6b8d12a-d221-4cbb-9dcb-b966626ee7e9")]
            public virtual RepoItemInfo HomepageMenuInfo
            {
                get
                {
                    return _homepagemenuInfo;
                }
            }

            /// <summary>
            /// The Linear folder.
            /// </summary>
            [RepositoryFolder("b4d7b99d-a7e0-407f-872b-315be946aa79")]
            public virtual e3ValidationRepositoryFolders.LinearFolder Linear
            {
                get { return _linear; }
            }
        }

        /// <summary>
        /// The LinearFolder folder.
        /// </summary>
        [RepositoryFolder("b4d7b99d-a7e0-407f-872b-315be946aa79")]
        public partial class LinearFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usernamefieldInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _passwordfieldInfo;
            RepoItemInfo _arrowbuttonInfo;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _qaprodtestInfo;

            /// <summary>
            /// Creates a new Linear  folder.
            /// </summary>
            public LinearFolder(RepoGenBaseFolder parentFolder) :
                    base("Linear", "form[@title='MainActivity']/container[@rid='content']/container[@containertype='Linear']", parentFolder, 30000, null, false, "b4d7b99d-a7e0-407f-872b-315be946aa79", "")
            {
                _usernamefieldInfo = new RepoItemInfo(this, "UsernameField", ".//androidelement[@contentdescription='stackLayout']/androidelement[5]/androidelement[1]/androidelement[1]/androidelement[2]/text[@contentdescription='username']", 30000, null, "0c8348c8-d0d9-44bb-bb6f-3ff284bc136d");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//androidelement[@contentdescription='stackLayout']/androidelement[5]/androidelement[1]/androidelement[1]/androidelement[5]/text[@contentdescription='password']", 30000, null, "6cff53ce-c90d-4a26-b754-bafc58146d21");
                _passwordfieldInfo = new RepoItemInfo(this, "PasswordField", "androidelement/androidelement/androidelement/androidelement[1]/?/?/androidelement[@contentdescription='stackLayout']/androidelement[5]/androidelement[1]/androidelement[1]/androidelement[5]", 30000, null, "23038f38-9dc9-4185-ab04-1dd003d3a033");
                _arrowbuttonInfo = new RepoItemInfo(this, "ArrowButton", ".//androidelement[@contentdescription='stackLayout']/androidelement[5]/androidelement[1]/androidelement[1]/androidelement[6]/picture[@contentdescription='Login']", 30000, null, "45779816-d218-4033-b4d6-3164ec9e083c");
                _logoutInfo = new RepoItemInfo(this, "Logout", "androidelement/androidelement/androidelement[2]//list[@contentdescription='listView']/androidelement[10]/androidelement/androidelement/androidelement[2]/text", 30000, null, "67f071e1-9837-4825-b0bc-963ee2eda7d1");
                _qaprodtestInfo = new RepoItemInfo(this, "QaProdTest", ".//androidelement[@contentdescription='stackLayout']/androidelement[1]/text", 30000, null, "c588f49b-7635-4670-9f5e-c45c68c190fe");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b4d7b99d-a7e0-407f-872b-315be946aa79")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b4d7b99d-a7e0-407f-872b-315be946aa79")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UsernameField item.
            /// </summary>
            [RepositoryItem("0c8348c8-d0d9-44bb-bb6f-3ff284bc136d")]
            public virtual Ranorex.Text UsernameField
            {
                get
                {
                    return _usernamefieldInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The UsernameField item info.
            /// </summary>
            [RepositoryItemInfo("0c8348c8-d0d9-44bb-bb6f-3ff284bc136d")]
            public virtual RepoItemInfo UsernameFieldInfo
            {
                get
                {
                    return _usernamefieldInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("6cff53ce-c90d-4a26-b754-bafc58146d21")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("6cff53ce-c90d-4a26-b754-bafc58146d21")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The PasswordField item.
            /// </summary>
            [RepositoryItem("23038f38-9dc9-4185-ab04-1dd003d3a033")]
            public virtual Ranorex.AndroidElement PasswordField
            {
                get
                {
                    return _passwordfieldInfo.CreateAdapter<Ranorex.AndroidElement>(true);
                }
            }

            /// <summary>
            /// The PasswordField item info.
            /// </summary>
            [RepositoryItemInfo("23038f38-9dc9-4185-ab04-1dd003d3a033")]
            public virtual RepoItemInfo PasswordFieldInfo
            {
                get
                {
                    return _passwordfieldInfo;
                }
            }

            /// <summary>
            /// The ArrowButton item.
            /// </summary>
            [RepositoryItem("45779816-d218-4033-b4d6-3164ec9e083c")]
            public virtual Ranorex.Picture ArrowButton
            {
                get
                {
                    return _arrowbuttonInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The ArrowButton item info.
            /// </summary>
            [RepositoryItemInfo("45779816-d218-4033-b4d6-3164ec9e083c")]
            public virtual RepoItemInfo ArrowButtonInfo
            {
                get
                {
                    return _arrowbuttonInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("67f071e1-9837-4825-b0bc-963ee2eda7d1")]
            public virtual Ranorex.Text Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("67f071e1-9837-4825-b0bc-963ee2eda7d1")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The QaProdTest item.
            /// </summary>
            [RepositoryItem("c588f49b-7635-4670-9f5e-c45c68c190fe")]
            public virtual Ranorex.Text QaProdTest
            {
                get
                {
                    return _qaprodtestInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The QaProdTest item info.
            /// </summary>
            [RepositoryItemInfo("c588f49b-7635-4670-9f5e-c45c68c190fe")]
            public virtual RepoItemInfo QaProdTestInfo
            {
                get
                {
                    return _qaprodtestInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
