///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace e3Validation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The startE3App recording.
    /// </summary>
    [TestModule("69381ff6-d6ca-4649-a634-0d7614201b81", ModuleType.Recording, 1)]
    public partial class startE3App : ITestModule
    {
        /// <summary>
        /// Holds an instance of the e3ValidationRepository repository.
        /// </summary>
        public static e3ValidationRepository repo = e3ValidationRepository.Instance;

        static startE3App instance = new startE3App();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public startE3App()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static startE3App Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run mobile app 'com.enclarapharmacia.E3Mobileapp' on device 'SM-G960U'.", new RecordItemIndex(0));
            Host.Local.RunMobileApp("SM-G960U", "com.enclarapharmacia.E3Mobileapp", true);
            Delay.Milliseconds(3500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
